### ISSUE TITLE
test prediction

### ISSUE THREAD

**Issue by JenniferTanH** [yashsmehta/personality-prediction#3]
How to get a personality prediction of an unseen text after training?

**Comment by yashsmehta** [comment]
Currently, our code doesn't have checkpointing and model saving built-in as the time for training the fine-tuning model (e.g. MLP) is relatively less (~1hr). For getting prediction on unseen text, you will first have to extract the features from the unseen text by passing it through the Language Model (use LM_extractor.py). After getting the .pkl file, load this and pass it through as you would on any PyTorch trained model.

Hope this helps!

**Comment by JenniferTanH** [comment]
Thank you for your reply!
But I got another problem with the essay.csv, it seems only has five samples, which causes an error when running fine-tuning model (e.g., MLP_LM.py)

> ValueError: Cannot have number of splits n_splits=10 greater than the number of samples: n_samples=5.

**Comment by Arkhemis** [comment]
@yashsmehta Would it be possible for you to explain the steps as to get the personality of users from a custom text? I'm struggling to understand how to use the LM_extractor.py, since it only accepts essays or kaggle parameters, with both having specific Mairesse features attached (which would not be the case of a custom dataset). Thank you!

**Comment by saminfatehi** [comment]
Hi @Arkhemis,

You can use models that need only the linguistic features (like BERTand ALBERT, which in LM_extractor.py we extract). SVM_LM.py and MLP_LM.py (in finetune_models) don't need Mairesse or other psycho-linguistic features and they only use BERT/ALBERT features.

**Comment by saminfatehi** [comment]
Hi @JenniferTanH,

I modified the input file. You can try again. :)

**Comment by JenniferTanH** [comment]
@saminfatehir 

I see, thanks!

**Comment by PrekshyaBasnet** [comment]
@yashsmehta @saminfatehir 

I am trying to predict the traits for a custom text dataset, so after creating a pickle file, I am confused on how to predict it without having to train the dataset again? I was trying to save the previously trained model but in the MLP_combined_features.py for every iteration of traits, the model is created, I don't know how to save them or how to use a single model instead.

Would appreciate any help!

Thank you for this wonderful work!

**Update**

So I was trying to understand the **training** function:
- If I add a softmax in the final dense layer and then output the prediction ranging 0 to 1 can I interpret the result with the interval of the given confidence?

Q1
For example, for y_val = [1. 0.] (first column for N, second for Y) , if it predicted y_predicted = [0.838 0.162] for Extraversion, 
Can I interpret this as, for the given text, with 83.8% confidence it is not Extraversion or it is Extraversion with 16% confidence?

Q2
I am also thinking that with the currently implementation, I should add additional code to save model for each trait with the best hyper parameter to use it for custom text, is this what needs to be done for testing custom text? 

Thanks 😊

**Comment by yashsmehta** [comment]
Hi Prekshya, 

Thanks for the interest in our work.
The main computationally heavy part of the model is passing the text through the language model (e.g. BERT, this is being done in LM_extractor.py) and will output a .pickle file. Since you already have the pickle file, now training the MLP from scratch will be done very quickly and not require much resources (I would approximate <30m on your local CPU). In this scenario, there wouldn't be the need to save the model... 

The downside is, let's say you want to train on some data and test on another, you should have the LM features for both of these splits. There can be 2 ways of doing this -- 
1) either pass the entire data to the LM_extractor.py 
2) just pass the training data, train the MLP (or the fine-tuning model of your choice) and save the model. Now for your test set, you can pass the data through a pretrained LM (using the hugging face implementation) and without saving the features into a pickle file, directly pass these features into your trained MLP.

Q1 - yes, you can interpret it that way.
Q2 - since the fine-tuning models do not require a large amount of compute, we tested hyperparams online itself and didn't write a pipeline to save the model parameters. But this is definitely a good idea and would be useful to have in the code.

hope this helps!

**Comment by PrekshyaBasnet** [comment]
@yashsmehta Thank you for your feedback! 

Yes I am trying the method as mentioned in 2 by first training the MLP, saving the model and and using this predict for the extracted Bert embedding from a custom text!

Thank you!
